spring.application.name=Usuarios
server.port = 9000

# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Test_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Crear o actualizar tablas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true